
import json
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import admin_page_add
import admin_page_remove
import admin_page_modify
import main_page

class Admin_Page_View:

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x700+455+44")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Ship_Ba_Admin_View")
        top.configure(background="#d1c9ad")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top
        self.data_wallet = json.load(open('backend/wallet.json'))
        self.data_material = json.load(open('backend/raw_material.json'))

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.197, rely=0.027, height=91, width=194)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d1c9ad")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Comic Sans MS} -size 36")
        self.Label1.configure(foreground="#6d5741")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''ADMIN''')

        self.Admin_logo = tk.Label(self.top)
        self.Admin_logo.place(relx=0.033, rely=0.014, height=111, width=94)
        self.Admin_logo.configure(activebackground="#f9f9f9")
        self.Admin_logo.configure(activeforeground="black")
        self.Admin_logo.configure(anchor='w')
        self.Admin_logo.configure(background="#d1c9ad")
        self.Admin_logo.configure(compound='left')
        self.Admin_logo.configure(disabledforeground="#a3a3a3")
        self.Admin_logo.configure(foreground="#000000")
        self.Admin_logo.configure(highlightbackground="#d9d9d9")
        self.Admin_logo.configure(highlightcolor="black")
        photo_location = "./menu/addmin.png"
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Admin_logo.configure(image=_img0)

        self.Label3 = tk.Label(self.top)
        self.Label3.place(relx=0.853, rely=0.181, height=82, width=74)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d1c9ad")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        photo_location = "./menu/Logo3.png"
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.Label3.configure(image=_img1)

        self.TSeparator1 = ttk.Separator(self.top)
        self.TSeparator1.place(relx=0.533, rely=0.093,  relwidth=0.467)

        self.Button_add = tk.Button(self.top)
        self.Button_add.place(relx=0.048, rely=0.203, height=45, width=110)
        self.Button_add.configure(activebackground="#ececec")
        self.Button_add.configure(activeforeground="#000000")
        self.Button_add.configure(background="#d1c9ad")
        self.Button_add.configure(compound='left')
        self.Button_add.configure(cursor="hand2")
        self.Button_add.configure(disabledforeground="#a3a3a3")
        self.Button_add.configure(foreground="#000000")
        self.Button_add.configure(highlightbackground="#d9d9d9")
        self.Button_add.configure(highlightcolor="black")
        photo_location = "./menu/Button_add.png"
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.Button_add.configure(image=_img2)
        self.Button_add.configure(pady="0")
        self.Button_add.configure(relief="flat")
        self.Button_add.configure(command=self.open_admin_add)

        self.Button_remove = tk.Button(self.top)
        self.Button_remove.place(relx=0.24, rely=0.2, height=45, width=110)
        self.Button_remove.configure(activebackground="#ececec")
        self.Button_remove.configure(activeforeground="#000000")
        self.Button_remove.configure(background="#d1c9ad")
        self.Button_remove.configure(compound='left')
        self.Button_remove.configure(cursor="hand2")
        self.Button_remove.configure(disabledforeground="#a3a3a3")
        self.Button_remove.configure(foreground="#000000")
        self.Button_remove.configure(highlightbackground="#d9d9d9")
        self.Button_remove.configure(highlightcolor="black")
        photo_location = "./menu/Button_remove.png"
        global _img3
        _img3 = tk.PhotoImage(file=photo_location)
        self.Button_remove.configure(image=_img3)
        self.Button_remove.configure(pady="0")
        self.Button_remove.configure(relief="flat")
        self.Button_remove.configure(command=self.open_admin_remove)

        self.Button_view = tk.Button(self.top)
        self.Button_view.place(relx=0.65, rely=0.2, height=45, width=110)
        self.Button_view.configure(activebackground="#ececec")
        self.Button_view.configure(activeforeground="#000000")
        self.Button_view.configure(background="#d1c9ad")
        self.Button_view.configure(compound='left')
        self.Button_view.configure(cursor="hand2")
        self.Button_view.configure(disabledforeground="#a3a3a3")
        self.Button_view.configure(foreground="#000000")
        self.Button_view.configure(highlightbackground="#d9d9d9")
        self.Button_view.configure(highlightcolor="black")
        photo_location = "./menu/Button_view.png"
        global _img4
        _img4 = tk.PhotoImage(file=photo_location)
        self.Button_view.configure(image=_img4)
        self.Button_view.configure(pady="0")
        self.Button_view.configure(relief="flat")

        self.Button_home = tk.Button(self.top)
        self.Button_home.place(relx=0.033, rely=0.914, height=45, width=110)
        self.Button_home.configure(activebackground="#ececec")
        self.Button_home.configure(activeforeground="#000000")
        self.Button_home.configure(background="#d1c9ad")
        self.Button_home.configure(compound='left')
        self.Button_home.configure(cursor="hand2")
        self.Button_home.configure(disabledforeground="#a3a3a3")
        self.Button_home.configure(foreground="#000000")
        self.Button_home.configure(highlightbackground="#d9d9d9")
        self.Button_home.configure(highlightcolor="black")
        photo_location = "./menu/home.png"
        global _img5
        _img5 = tk.PhotoImage(file=photo_location)
        self.Button_home.configure(image=_img5)
        self.Button_home.configure(pady="0")
        self.Button_home.configure(relief="flat")
        self.Button_home.configure(command=self.open_admin_home)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.033, rely=0.286, relheight=0.55, relwidth=0.942)

        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#f2ebe3")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.027, rely=0.042, height=31, width=174)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#f2ebe3")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Comic Sans MS} -size 18 -underline 1")
        self.Label2.configure(foreground="#6d5741")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''VIEW ADMIN''')

        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.018, rely=0.156, relheight=0.818
                , relwidth=0.965)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#f2ebe3")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Label4 = tk.Label(self.Frame2)
        self.Label4.place(relx=0.316, rely=0.413, height=21, width=194)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#f2ebe3")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Comic Sans MS} -size 12")
        self.Label4.configure(foreground="#6d5741")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Available Raw Materials''')

        self.TSeparator2 = ttk.Separator(self.Frame2)
        self.TSeparator2.place(relx=0.044, rely=0.451,  relwidth=0.261)

        self.TSeparator3 = ttk.Separator(self.Frame2)
        self.TSeparator3.place(relx=0.668, rely=0.454,  relwidth=0.292)

        self.Label5 = tk.Label(self.Frame2)
        self.Label5.place(relx=0.055, rely=0.54, height=21, width=74)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#f2ebe3")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Comic Sans MS} -size 12")
        self.Label5.configure(foreground="#6d5741")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Coffee  :''')

        self.Label6 = tk.Label(self.Frame2)
        self.Label6.place(relx=0.05, rely=0.835, height=21, width=44)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#f2ebe3")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="-family {Comic Sans MS} -size 12")
        self.Label6.configure(foreground="#6d5741")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Ice  :''')

        self.Label7 = tk.Label(self.Frame2)
        self.Label7.place(relx=0.048, rely=0.921, height=21, width=54)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(anchor='w')
        self.Label7.configure(background="#f2ebe3")
        self.Label7.configure(compound='left')
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font="-family {Comic Sans MS} -size 12")
        self.Label7.configure(foreground="#6d5741")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Milk  :''')

        self.Label8 = tk.Label(self.Frame2)
        self.Label8.place(relx=0.587, rely=0.54, height=21, width=94)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(anchor='w')
        self.Label8.configure(background="#f2ebe3")
        self.Label8.configure(compound='left')
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(font="-family {Comic Sans MS} -size 12")
        self.Label8.configure(foreground="#6d5741")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Milk Foam  :''')

        self.Label9 = tk.Label(self.Frame2)
        self.Label9.place(relx=0.259, rely=0.149, height=31, width=144)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(anchor='w')
        self.Label9.configure(background="#f2ebe3")
        self.Label9.configure(compound='left')
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(font="-family {Comic Sans MS} -size 16")
        self.Label9.configure(foreground="#6d5741")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Total Sales  :''')

        self.Label_tolal = tk.Label(self.Frame2)
        self.Label_tolal.place(relx=0.527, rely=0.133, height=41, width=134)
        self.Label_tolal.configure(activebackground="#f9f9f9")
        self.Label_tolal.configure(activeforeground="black")
        self.Label_tolal.configure(anchor='w')
        self.Label_tolal.configure(background="#f2ebe3")
        self.Label_tolal.configure(compound='left')
        self.Label_tolal.configure(disabledforeground="#a3a3a3")
        self.Label_tolal.configure(font="-family {Comic Sans MS} -size 20")
        self.Label_tolal.configure(foreground="#6d5741")
        self.Label_tolal.configure(highlightbackground="#d9d9d9")
        self.Label_tolal.configure(highlightcolor="black")
        self.Label_tolal.configure(text=f'{self.data_wallet["Total Amount"]} ฿')

        self.Label_coffee = tk.Label(self.Frame2)
        self.Label_coffee.place(relx=0.198, rely=0.54, height=21, width=170)
        self.Label_coffee.configure(activebackground="#f9f9f9")
        self.Label_coffee.configure(activeforeground="black")
        self.Label_coffee.configure(anchor='w')
        self.Label_coffee.configure(background="#f2ebe3")
        self.Label_coffee.configure(compound='left')
        self.Label_coffee.configure(disabledforeground="#a3a3a3")
        self.Label_coffee.configure(font="-family {Comic Sans MS} -size 12")
        self.Label_coffee.configure(foreground="#6d5741")
        self.Label_coffee.configure(highlightbackground="#d9d9d9")
        self.Label_coffee.configure(highlightcolor="black")
        self.Label_coffee.configure(text=f'{self.data_material["coffee"]} g')

        self.Label_tea_cocoa = tk.Label(self.Frame2)
        self.Label_tea_cocoa.place(relx=0.3, rely=0.638, height=21, width=160)
        self.Label_tea_cocoa.configure(activebackground="#f9f9f9")
        self.Label_tea_cocoa.configure(activeforeground="black")
        self.Label_tea_cocoa.configure(anchor='w')
        self.Label_tea_cocoa.configure(background="#f2ebe3")
        self.Label_tea_cocoa.configure(compound='left')
        self.Label_tea_cocoa.configure(disabledforeground="#a3a3a3")
        self.Label_tea_cocoa.configure(font="-family {Comic Sans MS} -size 12")
        self.Label_tea_cocoa.configure(foreground="#6d5741")
        self.Label_tea_cocoa.configure(highlightbackground="#d9d9d9")
        self.Label_tea_cocoa.configure(highlightcolor="black")
        self.Label_tea_cocoa.configure(text=f'{self.data_material["tea_coco"]} g')

        self.Label_ice = tk.Label(self.Frame2)
        self.Label_ice.place(relx=0.143, rely=0.835, height=21, width=200)
        self.Label_ice.configure(activebackground="#f9f9f9")
        self.Label_ice.configure(activeforeground="black")
        self.Label_ice.configure(anchor='w')
        self.Label_ice.configure(background="#f2ebe3")
        self.Label_ice.configure(compound='left')
        self.Label_ice.configure(disabledforeground="#a3a3a3")
        self.Label_ice.configure(font="-family {Comic Sans MS} -size 12")
        self.Label_ice.configure(foreground="#6d5741")
        self.Label_ice.configure(highlightbackground="#d9d9d9")
        self.Label_ice.configure(highlightcolor="black")
        self.Label_ice.configure(text=f'{self.data_material["Ice"]} ml')

        self.Label_milk = tk.Label(self.Frame2)
        self.Label_milk.place(relx=0.163, rely=0.921, height=21, width=170)
        self.Label_milk.configure(activebackground="#f9f9f9")
        self.Label_milk.configure(activeforeground="black")
        self.Label_milk.configure(anchor='w')
        self.Label_milk.configure(background="#f2ebe3")
        self.Label_milk.configure(compound='left')
        self.Label_milk.configure(disabledforeground="#a3a3a3")
        self.Label_milk.configure(font="-family {Comic Sans MS} -size 12")
        self.Label_milk.configure(foreground="#6d5741")
        self.Label_milk.configure(highlightbackground="#d9d9d9")
        self.Label_milk.configure(highlightcolor="black")
        self.Label_milk.configure(text=f'{self.data_material["Milk"]}  ml')

        self.Label10 = tk.Label(self.Frame2)
        self.Label10.place(relx=0.05, rely=0.635, height=21, width=120)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(anchor='w')
        self.Label10.configure(background="#f2ebe3")
        self.Label10.configure(compound='left')
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(font="-family {Comic Sans MS} -size 12")
        self.Label10.configure(foreground="#6d5741")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''Tea and Cocoa  :''')

        self.Label11 = tk.Label(self.Frame2)
        self.Label11.place(relx=0.05, rely=0.737, height=21, width=74)
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(activeforeground="black")
        self.Label11.configure(anchor='w')
        self.Label11.configure(background="#f2ebe3")
        self.Label11.configure(compound='left')
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(font="-family {Comic Sans MS} -size 12")
        self.Label11.configure(foreground="#6d5741")
        self.Label11.configure(highlightbackground="#d9d9d9")
        self.Label11.configure(highlightcolor="black")
        self.Label11.configure(text='''Water  :''')

        self.Label12 = tk.Label(self.Frame2)
        self.Label12.place(relx=0.587, rely=0.667, height=21, width=74)
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(activeforeground="black")
        self.Label12.configure(anchor='w')
        self.Label12.configure(background="#f2ebe3")
        self.Label12.configure(compound='left')
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(font="-family {Comic Sans MS} -size 12")
        self.Label12.configure(foreground="#6d5741")
        self.Label12.configure(highlightbackground="#d9d9d9")
        self.Label12.configure(highlightcolor="black")
        self.Label12.configure(text='''bubble  :''')

        self.Label13 = tk.Label(self.Frame2)
        self.Label13.place(relx=0.589, rely=0.784, height=21, width=64)
        self.Label13.configure(activebackground="#f9f9f9")
        self.Label13.configure(activeforeground="black")
        self.Label13.configure(anchor='w')
        self.Label13.configure(background="#f2ebe3")
        self.Label13.configure(compound='left')
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(font="-family {Comic Sans MS} -size 12")
        self.Label13.configure(foreground="#6d5741")
        self.Label13.configure(highlightbackground="#d9d9d9")
        self.Label13.configure(highlightcolor="black")
        self.Label13.configure(text='''Sugar  :''')

        self.Label14 = tk.Label(self.Frame2)
        self.Label14.place(relx=0.587, rely=0.902, height=21, width=74)
        self.Label14.configure(activebackground="#f9f9f9")
        self.Label14.configure(activeforeground="black")
        self.Label14.configure(anchor='w')
        self.Label14.configure(background="#f2ebe3")
        self.Label14.configure(compound='left')
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(font="-family {Comic Sans MS} -size 12")
        self.Label14.configure(foreground="#6d5741")
        self.Label14.configure(highlightbackground="#d9d9d9")
        self.Label14.configure(highlightcolor="black")
        self.Label14.configure(text='''Straw  :''')

        self.Label_water = tk.Label(self.Frame2)
        self.Label_water.place(relx=0.189, rely=0.74, height=21, width=184)
        self.Label_water.configure(activebackground="#f9f9f9")
        self.Label_water.configure(activeforeground="black")
        self.Label_water.configure(anchor='w')
        self.Label_water.configure(background="#f2ebe3")
        self.Label_water.configure(compound='left')
        self.Label_water.configure(disabledforeground="#a3a3a3")
        self.Label_water.configure(font="-family {Comic Sans MS} -size 12")
        self.Label_water.configure(foreground="#6d5741")
        self.Label_water.configure(highlightbackground="#d9d9d9")
        self.Label_water.configure(highlightcolor="black")
        self.Label_water.configure(text=f'{self.data_material["Water"]}  ml')

        self.Label_milk_foam = tk.Label(self.Frame2)
        self.Label_milk_foam.place(relx=0.774, rely=0.54, height=21, width=114)
        self.Label_milk_foam.configure(activebackground="#f9f9f9")
        self.Label_milk_foam.configure(activeforeground="black")
        self.Label_milk_foam.configure(anchor='w')
        self.Label_milk_foam.configure(background="#f2ebe3")
        self.Label_milk_foam.configure(compound='left')
        self.Label_milk_foam.configure(disabledforeground="#a3a3a3")
        self.Label_milk_foam.configure(font="-family {Comic Sans MS} -size 12")
        self.Label_milk_foam.configure(foreground="#6d5741")
        self.Label_milk_foam.configure(highlightbackground="#d9d9d9")
        self.Label_milk_foam.configure(highlightcolor="black")
        self.Label_milk_foam.configure(text=f'{self.data_material["Milk_Foam"]}  ml')

        self.Label_bubble = tk.Label(self.Frame2)
        self.Label_bubble.place(relx=0.728, rely=0.667, height=21, width=124)
        self.Label_bubble.configure(activebackground="#f9f9f9")
        self.Label_bubble.configure(activeforeground="black")
        self.Label_bubble.configure(anchor='w')
        self.Label_bubble.configure(background="#f2ebe3")
        self.Label_bubble.configure(compound='left')
        self.Label_bubble.configure(disabledforeground="#a3a3a3")
        self.Label_bubble.configure(font="-family {Comic Sans MS} -size 12")
        self.Label_bubble.configure(foreground="#6d5741")
        self.Label_bubble.configure(highlightbackground="#d9d9d9")
        self.Label_bubble.configure(highlightcolor="black")
        self.Label_bubble.configure(text=f'{self.data_material["bubble"]}  ml')

        self.Label_sugar = tk.Label(self.Frame2)
        self.Label_sugar.place(relx=0.717, rely=0.784, height=21, width=124)
        self.Label_sugar.configure(activebackground="#f9f9f9")
        self.Label_sugar.configure(activeforeground="black")
        self.Label_sugar.configure(anchor='w')
        self.Label_sugar.configure(background="#f2ebe3")
        self.Label_sugar.configure(compound='left')
        self.Label_sugar.configure(disabledforeground="#a3a3a3")
        self.Label_sugar.configure(font="-family {Comic Sans MS} -size 12")
        self.Label_sugar.configure(foreground="#6d5741")
        self.Label_sugar.configure(highlightbackground="#d9d9d9")
        self.Label_sugar.configure(highlightcolor="black")
        self.Label_sugar.configure(text=f'{self.data_material["sugar"]}  g')

        self.Label_straw = tk.Label(self.Frame2)
        self.Label_straw.place(relx=0.717, rely=0.905, height=21, width=124)
        self.Label_straw.configure(activebackground="#f9f9f9")
        self.Label_straw.configure(activeforeground="black")
        self.Label_straw.configure(anchor='w')
        self.Label_straw.configure(background="#f2ebe3")
        self.Label_straw.configure(compound='left')
        self.Label_straw.configure(disabledforeground="#a3a3a3")
        self.Label_straw.configure(font="-family {Comic Sans MS} -size 12")
        self.Label_straw.configure(foreground="#6d5741")
        self.Label_straw.configure(highlightbackground="#d9d9d9")
        self.Label_straw.configure(highlightcolor="black")
        self.Label_straw.configure(text=f'{self.data_material["straw"]}  piece')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.443, rely=0.2, height=45, width=110)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d1c9ad")
        self.Button2.configure(compound='left')
        self.Button2.configure(cursor="hand2")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        photo_location = "./menu/modify.png"
        global _img6
        _img6 = tk.PhotoImage(file=photo_location)
        self.Button2.configure(image=_img6)
        self.Button2.configure(pady="0")
        self.Button2.configure(relief="flat")
        self.Button2.configure(command=self.open_admin_modify)

    def open_admin_add(self):
        self.top.destroy()
        admin_page_add.main_loop()

    def open_admin_remove(self):
        self.top.destroy()
        admin_page_remove.main_loop()

    def open_admin_modify(self):
        self.top.destroy()
        admin_page_modify.main_loop()

    def open_admin_home(self):
        self.top.destroy()
        main_page.main_loop()

def main_loop(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = Admin_Page_View(_top1)
    root.mainloop()

if __name__ == '__main__':
    main_loop()

